language: c
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "y5Q9T5dcFVymCURzA4ITCUVEoHGi4APIUUevkYld4ho/zwWsI+Hhj22wukpNi3Fva3/QYORj1jrDS19OnZ2sSDGgJ0Bb6bNHwWmf7nacIAmWJvx93sqfGSJT2VRg7eMhFcDhbFLCuQ+hgoOIn5T4tstYKgSQUubwUN/J5ZjRgVZrRZ8TvYE8d8pnKdshYJteeGENDccR7yXYK6KDkFVciCr+FE2epwtcauv1E3su+PptCg5TmbtXzG/BBqFfvxzodGhDHxqT3mVWyMX3jgiS4GJv9hNTQva8AKh/9A9pWGfxCfMQMk1mPV+I/g9MooIqkIJPPBOae6ih4xPViasR15rWBSF1MRjC2cc2Ad74pn+UhtO+przJvBqBk11Xy4L7IT23LLo2GfMPYHuj6tAUQbXAsXR75RP/njSKbnIPoZ6VjwkkGPQQWEePPTdf6Lx5stCZoWj977KqMmudBCDi9GLjWxt5JpTwM+2oGmT6IM5byt7HChAmDieP2+eHUmWbBp+iluXkayOD+vriwJZzwiM2GPzFoc78MiMpvDYQHhhInDcE/UiyJYbvb/2YOFg1Jsd1/i3N1X/Ja1DjUQgTPmcnTfdSMXfbeDnP6av4yKsLuTWDRqW5gkUWanQPtuIqI7IXTeB+lWwvLSJBR/40hHrMwdRWrTKg2WTDZTAD0Bo="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_script:
  - export CC=i686-w64-mingw32-gcc

addons:
  coverity_scan:
    project:
      name: "katakk/pkill"
      description: "Build submitted via Travis CI"
    build_command:   "make"
    branch_pattern: master
  apt:
    packages:
      - binutils-mingw-w64-i686
      - gcc-mingw-w64-i686
      - wine

script:
  - make

deploy:
  provider: releases
  api_key:
    - secure: "ktFMoFgg2B8X+eTT4U8vJroJIoD6S63eh3w/K1gC7f5rF1qb1WbFuiUPV7qv2+wi6HC9aCVPPLq7j7Glkr6qYqeDbc8dsNtz2xKVprEp+02Wn3F2Qf0IZXp6twOteE6bWxGvcbjmWbFz6v4OpkFQ0xzhPiG8R+nrhEZ9d6jhzgsLX0DFByhlXqtgFVHSSzbsjHjQcY/ATaj70gnvb6TJh8PaOy2oLP5K7I3tOgOtrhqBi8aU/rA4ox7vTptPVaHHkv/i8lzCSZYt0bQw6KvjWe4Vq78A4IOMuN+SAqquwTnjJNEIKvWT3hBpSJN9DSmmQ65mwuBoDUia0Yyp/hGBjHdnch2b081/Jv5TUNAGILCMCIvtbwb7/khtt5GhDOaKo282UG4wmhcn9HqrMJOicb8BaSkdHnpyeVR2waFIkpfzbh8RWTWauYACV1lBNJ6LSjao/LQrTJ7RTw7Ad+co4foG1BmwaOjKln+HBRHMFA2igNCcvH3znrJBSEvDiuOCDyAyvok1pPGpdmguCVQiVnH69nU9EU6g14rAg0dO9lVi6x6mrHHB4J1Xmep+8U2oAjrfemgHbNo7g6pu7fUJPdXOcfswYK8bIr4/KkNyFt+PIP7Pq18ZUo++BDt6m2OSU7ID/wnYB4iysmVT2yGNrrz6dsAAA7pZ00QpMzpjCus="
  file: pkill.zip
  skip_cleanup: true
  all_branches: true  # https://github.com/travis-ci/travis-ci/issues/1675
  on:
    tags: true
